# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "overlay" ];
  boot.initrd.systemd.enable = true;
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  
  hardware.nvidia = {
    powerManagement = {
      enable = true;
      finegrained = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4b6dcfa1-233c-4ac9-941f-253ee0a49c7b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d510872d-4892-4757-8f49-7f5aa822f50b".device = "/dev/disk/by-uuid/d510872d-4892-4757-8f49-7f5aa822f50b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0E3B-2733";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [
      { 
        device = "/swapfile";
        size = 20 * 1024;
      }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
